version: '3.4'

services:
  firstwebapi:
    image: ${DOCKER_REGISTRY-}firstwebapi
    build:
      context: .
      dockerfile: FirstWebAPI/Dockerfile

  APIsqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest

  secondwebapi:
    image: ${DOCKER_REGISTRY-}secondwebapi
    build:
      context: .
      dockerfile: SecondWebAPI/Dockerfile

