version: '3.4'

services:
  firstwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=APIsqldb,1433;Database=gatewayTest2; User=sa; Password=Password12*"

    ports:
      - "8002:80"
  APIsqldb:
    container_name: APIsqldb
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*


  secondwebapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=APIsqldb,1433;Database=gatewayTest2; User=sa; Password=Password12*"
    ports:
      - "5011:80"
    depends_on:
      - firstwebapi